#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -x /usr/bin/update-desktop-database ]; then
        /usr/bin/update-desktop-database -q /usr/share/applications || true
    fi
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
        /usr/bin/gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi
    if [ -x /usr/sbin/update-alternatives ] || [ -x /usr/bin/update-alternatives ]; then
        update-alternatives --remove x-www-browser /usr/bin/safeer 2>/dev/null || true
        update-alternatives --remove gnome-www-browser /usr/bin/safeer 2>/dev/null || true
    fi
fi

#DEBHELPER#

exit 0
