#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if [ -x /usr/bin/update-desktop-database ]; then
        /usr/bin/update-desktop-database -q /usr/share/applications || true
    fi

    if [ -x /usr/bin/gtk-update-icon-cache ]; then
        /usr/bin/gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi

    # Register Safeer Browser into Debian alternatives system for default browser
    if [ -x /usr/sbin/update-alternatives ] || [ -x /usr/bin/update-alternatives ]; then
        update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/safeer 40 || true
        update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/bin/safeer 40 || true
    fi
fi

#DEBHELPER#

exit 0
